name: Python formatting & testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - name: set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'  # cache dependencies
        cache-dependency-path: |
          requirements.txt
          requirements_dev.txt
    - name: install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt -r requirements_dev.txt

    - name: restore caches
      uses: actions/cache/restore@v3
      with:
        path: |
          .ruff_cache
          .pytest_cache
        # We want the latest cache to hit and be updated every time.
        key: lint-test-${{ github.run_id }}
        restore-keys: lint-test

    - name: lint
      run: |
        black --check .
        ruff .
    - name: test
      run: pytest

    - name: save caches
      uses: actions/cache/save@v3
      if: always()
      with:
        path: |
          .ruff_cache
          .pytest_cache
        key: lint-test-${{ github.run_id }}
