name: Python formatting & testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '3.12'

    - name: get exact Python version  # for busting the venv cache
      run: |
        echo "${{ steps.setup-python.outputs.python-version }}" > ".installed-python"
    - name: cache venv
      uses: actions/cache@v4
      id: cache-venv
      with:
        key: "venv-${{ hashFiles('.installed-python', 'requirements.txt') }}"
        # requirements_dev.txt is excluded, to not invalidate the cache if linters are updated
        path: |
          .venv/
    - name: create venv
      if: "steps.cache-venv.outputs.cache-hit == false"
      run: |
        python -m venv .venv
        .venv/bin/pip install --upgrade pip setuptools wheel
        .venv/bin/pip install -r requirements.txt -r requirements_dev.txt

    - name: restore linter caches
      uses: actions/cache/restore@v3
      with:
        path: |
          .ruff_cache
          .pytest_cache
        # We want the latest cache to hit and be updated every time.
        key: lint-test-${{ github.run_id }}
        restore-keys: lint-test
    - name: lint
      run: |
        .venv/bin/black --check .
        .venv/bin/ruff check .
    - name: test
      run: PYTHONPATH=$(pwd) .venv/bin/pytest
    - name: save linter caches
      uses: actions/cache/save@v3
      if: always()
      with:
        path: |
          .ruff_cache
          .pytest_cache
        key: lint-test-${{ github.run_id }}
